### ISSUE TITLE
cookieplone does not accept a project name that exists of only one word

### ISSUE THREAD

**Issue by fredvd** [plone/cookieplone#34]
cookieplone only accepts project names with multiple words. Otherwise there is a traceback.  For example a project name plone6test is not valid. 

```
 -> Setup Backend
Traceback (most recent call last):
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookieplone/generator.py", line 56, in generate
    result = cookiecutter(
             ^^^^^^^^^^^^^
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookiecutter/main.py", line 161, in cookiecutter
    prompt_for_config(context_for_prompting, no_input)
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookiecutter/prompt.py", line 283, in prompt_for_config
    cookiecutter_dict[key] = render_variable(env, raw, cookiecutter_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookiecutter/prompt.py", line 224, in render_variable
    return template.render(cookiecutter=cookiecutter_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/Users/fred/.local/pipx/venvs/cookieplone/lib/python3.12/site-packages/cookieplone/filters/__init__.py", line 14, in package_name
    return v.split(".")[1]
           ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by acsr** [comment]
same with Cookieplone 0.8.0 

A tripled namespace `test.plone.something` results in

``` shell
+ /home/astro/Plone6/Test/test-plone-something/backend/.venv/bin/uv pip install -r requirements-mxdev.txt
error: Build backend failed to determine requirements with `build_editable()` (exit status: 1)

[stderr]
error in test.plone.kwk setup command: Distribution contains no modules or packages for namespace package 'test.plone'
make[2]: *** [Makefile:69: build-dev] Error 2
make[2]: Leaving directory '/home/astro/Plone6/Test/test-plone-something/backend'
make[1]: *** [Makefile:63: backend-install] Error 2
make[1]: Leaving directory '/home/astro/Plone6/Test/test-plone-something'
make: *** [Makefile:89: install] Error 2
```

**Comment by davisagli** [comment]
@acsr The fix for this was just merged today in https://github.com/plone/cookieplone-templates/pull/86 -- please try again

**Comment by acsr** [comment]
THX here as well. works!
